name: Create File on Server

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and create file
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Created from GitHub Action" > ~/Documents/fromGhAction.txt
